name: xue_hua_video_snapshot
description: "Extract non-black cover candidate frames from video files across mobile and desktop platforms."
version: 1.0.0
homepage: https://github.com/Matkurban/xue_hua_video_snapshot
repository: https://github.com/Matkurban/xue_hua_video_snapshot
issue_tracker: https://github.com/Matkurban/xue_hua_video_snapshot/issues
documentation: https://github.com/Matkurban/xue_hua_video_snapshot/blob/main/README.md
changelog: https://github.com/Matkurban/xue_hua_video_snapshot/blob/main/CHANGELOG.md
license: MIT
license_file: LICENSE
author_email: matkurban@gmail.com
author_url: https://github.com/Matkurban
author_github: Matkurban

environment:
  sdk: ^3.12.0
  flutter: ^3.44.0

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  cross_file: ^0.3.5+2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kurban.xue_hua_video_snapshot
        pluginClass: XueHuaVideoSnapshotPlugin
      ios:
        pluginClass: XueHuaVideoSnapshotPlugin
      linux:
        pluginClass: XueHuaVideoSnapshotPlugin
      macos:
        pluginClass: XueHuaVideoSnapshotPlugin
      windows:
        pluginClass: XueHuaVideoSnapshotPluginCApi
