// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_VIDEO_DECODER_API_H_
#define PIGEON_VIDEO_DECODER_API_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace xue_hua_video_snapshot {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class VideoDecoderHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Generated class from Pigeon that represents data sent in messages.
class CaptureFrameResult {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit CaptureFrameResult(const std::vector<uint8_t>& rgba64);

  // Constructs an object setting all fields.
  explicit CaptureFrameResult(
    const std::vector<uint8_t>& rgba64,
    const std::string* png_path);

  // 64×64 RGBA pixels (16384 bytes).
  const std::vector<uint8_t>& rgba64() const;
  void set_rgba64(const std::vector<uint8_t>& value_arg);

  // Absolute path when [outputPath] was provided and write succeeded.
  const std::string* png_path() const;
  void set_png_path(const std::string_view* value_arg);
  void set_png_path(std::string_view value_arg);

  bool operator==(const CaptureFrameResult& other) const;
  bool operator!=(const CaptureFrameResult& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const CaptureFrameResult& obj);
 private:
  static CaptureFrameResult FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class VideoDecoderHostApi;
  friend class PigeonInternalCodecSerializer;
  std::vector<uint8_t> rgba64_;
  std::optional<std::string> png_path_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Native decode adapter: holds a decoder session open across probe + captures.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class VideoDecoderHostApi {
 public:
  VideoDecoderHostApi(const VideoDecoderHostApi&) = delete;
  VideoDecoderHostApi& operator=(const VideoDecoderHostApi&) = delete;
  virtual ~VideoDecoderHostApi() {}
  virtual void OpenSession(
    const std::string& url,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  virtual void ProbeDuration(
    int64_t session_id,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  virtual void CaptureFrame(
    int64_t session_id,
    int64_t position_ms,
    const std::string* output_path,
    std::function<void(ErrorOr<CaptureFrameResult> reply)> result) = 0;
  virtual void CloseSession(
    int64_t session_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by VideoDecoderHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `VideoDecoderHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    VideoDecoderHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    VideoDecoderHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  VideoDecoderHostApi() = default;
};
}  // namespace xue_hua_video_snapshot
#endif  // PIGEON_VIDEO_DECODER_API_H_
