// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum VideoDecoderApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct CaptureFrameResult: Hashable, CustomStringConvertible {
  /// 64×64 RGBA pixels (16384 bytes).
  var rgba64: FlutterStandardTypedData
  /// Absolute path when [outputPath] was provided and write succeeded.
  var pngPath: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureFrameResult? {
    let rgba64 = pigeonVar_list[0] as! FlutterStandardTypedData
    let pngPath: String? = nilOrValue(pigeonVar_list[1])

    return CaptureFrameResult(
      rgba64: rgba64,
      pngPath: pngPath
    )
  }
  func toList() -> [Any?] {
    return [
      rgba64,
      pngPath,
    ]
  }
  static func == (lhs: CaptureFrameResult, rhs: CaptureFrameResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VideoDecoderApiPigeonInternal.deepEquals(lhs.rgba64, rhs.rgba64) && VideoDecoderApiPigeonInternal.deepEquals(lhs.pngPath, rhs.pngPath)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CaptureFrameResult")
    VideoDecoderApiPigeonInternal.deepHash(value: rgba64, hasher: &hasher)
    VideoDecoderApiPigeonInternal.deepHash(value: pngPath, hasher: &hasher)
  }

  public var description: String {
    return "CaptureFrameResult(rgba64: \(String(describing: rgba64)), pngPath: \(String(describing: pngPath)))"
  }
}

private class VideoDecoderApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CaptureFrameResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class VideoDecoderApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CaptureFrameResult {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class VideoDecoderApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return VideoDecoderApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return VideoDecoderApiPigeonCodecWriter(data: data)
  }
}

class VideoDecoderApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = VideoDecoderApiPigeonCodec(readerWriter: VideoDecoderApiPigeonCodecReaderWriter())
}


/// Native decode adapter: holds a decoder session open across probe + captures.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VideoDecoderHostApi {
  func openSession(url: String, completion: @escaping (Result<Int64, Error>) -> Void)
  func probeDuration(sessionId: Int64, completion: @escaping (Result<Int64, Error>) -> Void)
  func captureFrame(sessionId: Int64, positionMs: Int64, outputPath: String?, completion: @escaping (Result<CaptureFrameResult, Error>) -> Void)
  func closeSession(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VideoDecoderHostApiSetup {
  static var codec: FlutterStandardMessageCodec { VideoDecoderApiPigeonCodec.shared }
  /// Sets up an instance of `VideoDecoderHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VideoDecoderHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_video_snapshot.VideoDecoderHostApi.openSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.openSession(url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openSessionChannel.setMessageHandler(nil)
    }
    let probeDurationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_video_snapshot.VideoDecoderHostApi.probeDuration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      probeDurationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = PigeonCodecHelpers.int64(from: args[0])
        api.probeDuration(sessionId: sessionIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      probeDurationChannel.setMessageHandler(nil)
    }
    let captureFrameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_video_snapshot.VideoDecoderHostApi.captureFrame\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      captureFrameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = PigeonCodecHelpers.int64(from: args[0])
        let positionMsArg = PigeonCodecHelpers.int64(from: args[1])
        let outputPathArg: String? = nilOrValue(args[2])
        api.captureFrame(sessionId: sessionIdArg, positionMs: positionMsArg, outputPath: outputPathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      captureFrameChannel.setMessageHandler(nil)
    }
    let closeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_video_snapshot.VideoDecoderHostApi.closeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = PigeonCodecHelpers.int64(from: args[0])
        api.closeSession(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeSessionChannel.setMessageHandler(nil)
    }
  }
}
